services:
 backend:
   build: 
      context: ./backend
   container_name: weather-backend
   ports:
     - "3000:3000"
   

 frontend:
   build: 
    context: ./frontend
   container_name: weather-frontend
   ports:
     - "80:80"
   depends_on:
     - backend
